language: haskell

ghc:
  - 7.6

before_install:
  - sudo apt-get install rtorrent screen
  - rtorrent -h | grep version
  - screen --version || true

install:
  - cabal sandbox init
  - ./dev/update-dependencies.sh

script:
  - cabal configure && cabal build
  - cabal configure -ftesting --enable-tests --enable-benchmark && cabal build && ./dist/build/spec/spec

notifications:
  email:
    on_success: never
    on_failure: change

  irc:
    channels:
      - "chat.freenode.net#haskell-bittorrent"
    on_success: change
    on_failure: change

    use_notice: true
    template:
      - "%{repository}#%{build_number} : %{message} for about %{duration}"
      - "Commit:  %{branch}/%{commit} by %{author}"
      - "Changes: %{compare_url}"
      - "Build:   %{build_url}"