language: haskell

notifications:
  email:
    on_success: never
    on_failure: change

  irc:
    channels:
      - "chat.freenode.net#haskell-bittorrent"
    on_success: always
    on_failure: always

ghc:
  - 7.4
  - 7.6

before_install:
  - sudo apt-get install rtorrent screen
  - rtorrent -h | grep version
  - screen --version

install:
  - cabal sandbox init
  - ./dev/update-dependencies.sh

script:
  - cabal configure --enable-tests --enable-benchmark && cabal build && ./dist/build/spec/spec