language: haskell

notifications:
  email: false

install:
  - cabal sandbox init
  - ./dev/update-dependencies.sh

script:
  - cabal configure --enable-tests --enable-benchmark && cabal build && ./dist/build/spec/spec